### ISSUE TITLE
What is this component all about?

### ISSUE THREAD

**Issue by bonzofenix** [cloudfoundry-incubator/routing-api#1]
Hi!
Would it be possible to get 1 or 2 paragraphs of the responsibilities of this components?
 I got it compiled on cf-210 and can not find information about it. Is there any place to read about it ?

Thanks!

**Comment by dieucao** [comment]
@bonzofenix 
The intention of the routing api is to help move registry of routes to the gorouter for internal components and services off of NATS.
The MVP is not to handle registering of routes for applications but this could be looked at in future.
You can find more about this in the routing-api proposal [1] and epic [2]

[1] https://docs.google.com/document/d/1iSrqmjRDEM0y_nIgk-iXNR9P-ODV7E-StN4UMj8y0lQ/edit?usp=sharing
[2] https://www.pivotaltracker.com/epic/show/1590160
