### ISSUE TITLE
HTTP routes API documentation misleadingly displays routes with IP addresses & ports

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-incubator/routing-api#10]
https://github.com/cloudfoundry-incubator/routing-api/blob/89560555e40ffd004d200ed38864eb62f9896756/docs/api_docs.md#example-response-3 lists 
> "route": "127.0.0.1:8080/routing"

Whereas I understand the gorouter HTTP routes should have FQDNs for the host part and likely the default port (80 or 443) (because the routing to apps is based on the ``Host`` header which is usually a FQDN and not the IP address of the load balancer)

Using examples such "route": "route.domain.org/routing" would make the experimental HTTP API easier to understand (similar to https://github.com/cloudfoundry-incubator/routing-api-cli#examples listing ""route":"mynewroute.com")

**Comment by shalako** [comment]
Hello @gberche-orange 

Yes, I can see why that would be confusing. I've updated the docs. 
https://github.com/cloudfoundry-incubator/routing-api/blob/master/docs/api_docs.md

Best,
Shannon

**Comment by gberche-orange** [comment]
thanks @shalako !
